[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "critical"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

chain = "classic"
base_path = "$HOME/.local/share/etc.io.parity.ethereum"
db_path = "$HOME/.local/share/etc.io.parity.ethereum/chains"
keys_path = "$HOME/.local/share/etc.io.parity.ethereum/keys"
identity = ""
light = true

[ui]
force = false
disable = true
port = 8180
interface = "127.0.0.1"
path = "$HOME/.local/share/io.parity.ethereum/signer"

[network]
port = 30503
min_peers = 25
max_peers = 50
nat = "any"
id = 1
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false

[rpc]
disable = false
port = 8555
interface = "local"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[websockets]
disable = true


[ipc]
disable = true


[dapps]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false


[snapshots]
disable_periodic = false


[misc]
color = true